AWSTemplateFormatVersion: 2010-09-09
Description: Template for bastion and compute node
Parameters:
  LabConstants:
    Type: String
    Description: Name of file containing constants for lab (<lab>-constants.yaml)
    Default: lab-constants.yaml

  EnclaveConstants:
    Type: String
    Description: Name of file containing constants for enclave
    Default: enclave-constants.yaml

  AdminPassword:
      Type: String
      NoEcho: true
      Description: Password for the ubuntu user

Mappings:
  LabConstants:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        # s3://<TemplateBucket>/<lab>-constants.yaml
        Location: !Sub s3://enclave-templates-${AWS::AccountId}-${AWS::Region}/${LabConstants}

  EnclaveConstants:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        # s3://<TemplateBucket>/<enclave>-constants.yaml
        Location: !Sub s3://enclave-templates-${AWS::AccountId}-${AWS::Region}/${EnclaveConstants}

Resources:
  #**************************
  # Lab Bastion
  #**************************
  Bastion:
    Type: 'AWS::EC2::Instance'
    Properties:
      #Instance type to be used for Bastion
      InstanceType: !FindInMap [LabConstants, Bastion, InstanceType]
      #AMI ID of image to use for Bastion.  Note this is region specific
      ImageId:
        Fn::ImportValue: "ec2-image-builder-BastionAMIId"
      MetadataOptions:
        HttpTokens: optional
        HttpEndpoint: enabled
        HttpPutResponseHopLimit: 1
      #Block Device Mappings
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            Encrypted: True
            KmsKeyId:
              Fn::ImportValue: "enclave-admin-EnclaveKmsKeyARN"

      #Subnet ID
      SubnetId:
        Fn::ImportValue: "enclave-vpc-BastionSubnet"
      #Bastion Security Group (defined below)
      SecurityGroupIds:
        - !GetAtt BastionSecurityGroup.GroupId
        - Fn::ImportValue: "enclave-vpc-EC2EndpointSG"
      #Key Pair used for instance management
      KeyName: !FindInMap [LabConstants, Bastion, KeyName]
      #instance profile
      IamInstanceProfile: !Ref BastionEC2InstanceProfile
      Tags:
        - Key: 'Name'
          Value:
            !Join
              - ''
              - - !FindInMap [LabConstants, Attributes, Name]
                - '-Bast'
        - Key: 'mcomm'
          Value: !FindInMap [LabConstants, Attributes, MComm]
        - Key: 'power_protect'
          Value: 'true'

  #**************************
  # EC2 Role
  #**************************

  #Role
  BastionEC2Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      #Policy
      Policies:
        - PolicyName:
            !Join
              - ''
              - - !FindInMap [LabConstants, Attributes, Name]
                - '-BastionPolicy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: 'Allow'
                Action: 'ec2:DescribeInstances'
                Resource: '*'
              - Effect: 'Allow'
                Action:
                  - 'ec2:StartInstances'
                  - 'ec2:StopInstances'
                Resource: '*'
                Condition:
                  StringEquals:
                    'ec2:ResourceTag/mcomm': !FindInMap [LabConstants, Attributes, MComm]
              - Effect: 'Allow'
                Action: 'kms:CreateGrant'
                Resource:
                  - Fn::ImportValue: "enclave-admin-EnclaveKmsKeyARN"
                Condition:
                  Bool:
                    'kms:GrantIsForAWSResource': true

  #Instance Profile
  BastionEC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName:
        !Join
          - ''
          - - !FindInMap [LabConstants, Attributes, Name]
            - '-BastionInstanceProfile'
      Path: '/'
      Roles:
        - Ref: 'BastionEC2Role'

  # Bastion Security Group
  BastionSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName:
        !Join
          - '-'
          - - !FindInMap [LabConstants, Attributes, Name]
            - 'BastionSecurityGroup'
      GroupDescription: 'Enable RDP'
      VpcId: 
        Fn::ImportValue: "enclave-vpc-EnclaveVPC"


  BastionSecurityGroupIngressVPN:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BastionSecurityGroup
      IpProtocol: tcp
      FromPort: 3389
      ToPort: 3389
      SourceSecurityGroupId:
        Fn::ImportValue: "client-vpn-SecurityGroup"

  #**************************
  # Lab Nodes
  #**************************
  # Duplicate Node resource block to create additional nodes
  Node01:
    Type: 'AWS::EC2::Instance'
    Properties:
      #Instance type to be used for Bastion
      InstanceType: !FindInMap [LabConstants, Node, InstanceType]
      #AMI ID of image to use for Bastion.  Note this is region specific
      ImageId:
        Fn::ImportValue: "ec2-image-builder-NodeAMIId"
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 330
            Encrypted: True
            KmsKeyId:
              Fn::ImportValue: "enclave-admin-EnclaveKmsKeyARN"
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: 20
            Encrypted: True
            KmsKeyId:
              Fn::ImportValue: "enclave-admin-EnclaveKmsKeyARN"

      #Subnet ID
      SubnetId: 
        Fn::ImportValue: "enclave-vpc-NodeSubnet"
      #Bastion Security Group (defined below)
      SecurityGroupIds:
        - !GetAtt NodeSecurityGroup.GroupId
        - Fn::ImportValue: "enclave-proxy-ProxySecurityGroup"
      #Key Pair used for instance management
      KeyName: !FindInMap [LabConstants, Node, KeyName]
      IamInstanceProfile:  !Ref NodeEC2InstanceProfile
      Tags:
        - Key: 'Name'
          Value:
            !Join
              - ''
              - - !FindInMap [LabConstants, Attributes, Name]
                - '-Node01'  #Change to match node name
        - Key: 'mcomm'
          Value: !FindInMap [LabConstants, Attributes, MComm]
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            PROXY="http://${ProxyIp}:3128"

            REGION=${AWS::Region}
            NO_PROXY_VALUE="s3.amazonaws.com,.s3.$REGION.amazonaws.com,169.254.169.254,localhost,127.0.0.1,::1"

            echo "http_proxy=$PROXY" >> /etc/environment
            echo "HTTP_PROXY=$PROXY" >> /etc/environment
            echo "https_proxy=$PROXY" >> /etc/environment
            echo "HTTPS_PROXY=$PROXY" >> /etc/environment
            echo "NO_PROXY=$NO_PROXY_VALUE" >> /etc/environment
            echo "no_proxy=$NO_PROXY_VALUE" >> /etc/environment

            echo "http_proxy=$PROXY; export http_proxy" >> /etc/bash.bashrc
            echo "HTTP_PROXY=$PROXY; export HTTP_PROXY" >> /etc/bash.bashrc
            echo "https_proxy=$PROXY; export https_proxy" >> /etc/bash.bashrc
            echo "HTTPS_PROXY=$PROXY; export HTTPS_PROXY" >> /etc/bash.bashrc
            echo "NO_PROXY=$NO_PROXY_VALUE; export NO_PROXY" >> /etc/bash.bashrc
            echo "no_proxy=$NO_PROXY_VALUE; export no_proxy" >> /etc/bash.bashrc

            echo "ubuntu:${AdminPassword}" | chpasswd
            passwd -u ubuntu

            reboot

          - NodeHostName: !Join
            - ''
            - - !FindInMap [LabConstants, Attributes, Name]
              - '-Node01'
            ProxyIp: !FindInMap [EnclaveConstants, Proxy, PrivateIpAddress]

  #**************************
  # EC2 Role
  #**************************

  #Role
  NodeEC2Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      #Policy
      Policies:
        - PolicyName:
            !Join
              - ''
              - - !FindInMap [LabConstants, Attributes, Name]
                - '-NodePolicy'
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObjectAcl'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                Resource: # arn:aws:s3:::<LabBucketIn>*
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref LabBucketIn
                      - '/*'
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:GetObjectAcl'
                  - 's3:GetObject'
                  - 's3:DeleteObject'
                Resource: # arn:aws:s3:::<LabBucketOut>/*
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref LabBucketOut
                      - '/*'
  #Instance Profile
  NodeEC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName:
        !Join
          - ''
          - - !FindInMap [LabConstants, Attributes, Name]
            - '-NodeInstanceProfile'
      Path: '/'
      Roles:
        - Ref: 'NodeEC2Role'

  NodeSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName:
        !Join
          - '-'
          - - !FindInMap [LabConstants, Attributes, Name]
            - 'NodeSecurityGroup'
      GroupDescription: 'Node Security Group'
      VpcId:
        Fn::ImportValue: "enclave-vpc-EnclaveVPC" 
  #Access form Bastion
  NodeSGIngress01:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      GroupId: !GetAtt NodeSecurityGroup.GroupId
      IpProtocol: 'tcp'
      FromPort: '3389'
      ToPort: '3389'
      SourceSecurityGroupId: !GetAtt BastionSecurityGroup.GroupId

  #**************************
  # Lab S3 Bucket
  #**************************

  #S3Bucket:
  LabBucketIn:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName:
        !Join
          - '-'
          - - !FindInMap [EnclaveConstants, Common, EnclavePrefix]
            - !FindInMap [LabConstants, Attributes, Name]
            - 'in'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      LoggingConfiguration:
        DestinationBucketName: !ImportValue "enclave-admin-LoggingBucket"
        LogFilePrefix: testing-logs
      VersioningConfiguration:
        Status: Enabled
  #S3Bucket:
  LabBucketOut:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName:
        !Join
          - '-'
          - - !FindInMap [EnclaveConstants, Common, EnclavePrefix]
            - !FindInMap [LabConstants, Attributes, Name]
            - 'out'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
      LoggingConfiguration:
        DestinationBucketName: !ImportValue "enclave-admin-LoggingBucket"
        LogFilePrefix: testing-logs
      VersioningConfiguration:
        Status: Enabled